image: node:10.15.1

cache:
  paths: 
    - node_modules/
    - .yarn

before_script:  
  - apt-get update -qq && apt-get install

stages: 
  - build

Build:
  stage: build
  tags:
    - node
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn build